# Generated by Django 5.2.17 on 2026-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='New Account', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=20),
        ),
    ]
