# Generated by Django 5.2.17 on 2026-09-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_name_alter_account_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='New Account', max_length=50),
        ),
    ]
